version: "3"
services:
  postgres:
    container_name: typescript_start_postgres
    image: postgres:latest
    ports:
      - "5436:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: typescript_start_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
